services:
  ghost:
    image: ghost:5.97.0-alpine  # Using Ghost version 5.97.0
    container_name: ghost_oneplusone
    restart: unless-stopped
    ports:
      - "2368:2368"  # GhostCMS default port
    environment:
      url: "https://ghost.mojah2.mojahmedia.net"  # Set your Ghost URL
      database__client: mysql  # Specify MariaDB as the database client
      database__connection__host: mysql  # MariaDB service name
      database__connection__user: ${GHOST_DB_USER}  # Set in .env file
      database__connection__password: ${GHOST_DB_PASSWORD}  # Set in .env file
      database__connection__database: ${GHOST_DB_NAME}  # Set in .env file
      cache__client: redis
      cache__connection__host: redis
    volumes:  # Mount directory for persistent data storage
      - /var/www/public/oneplusone/ghost:/var/lib/ghost/content  # Mount Ghost content directory
      - /var/www/private/docker/apps/config.production.json:/var/lib/ghost/config.production.json:ro  # Mount Ghost configuration file
    networks:
      - backend  # Use the shared backend network

networks:
  backend:
    external: true  # Use the existing backend network
