services:
  ghost:
    image: ghost:5.97.0-alpine  # Using Ghost version 5.97.0
    container_name: ghost_oneplusone
    restart: unless-stopped
    ports:
      - "2368:2368"  # GhostCMS default port
    environment:
      url: "https://ghost.mojah2.mojahmedia.net"  # Set your Ghost URL
      database__client: mysql  # Specify MariaDB as the database client
      database__connection__host: mariadb  # MariaDB service name
      database__connection__user: ${GHOST_DB_USER}  # Set in .env file
      database__connection__password: ${GHOST_DB_PASSWORD}  # Set in .env file
      database__connection__database: ${GHOST_DB_NAME}  # Set in .env file
    volumes:
      - /var/www/public/oneplusone/ghost:/var/lib/ghost/content  # Mount Ghost content directory
    networks:
      - backend  # Use the shared backend network
    depends_on:
      - mariadb:  # Ensure MariaDB is running before starting Ghost
          condition: service_started
  nginx:

  mariadb:
    image: mariadb:latest  # Use the latest version of MariaDB
    container_name: mariadb
    restart: unless-stopped  # Restart the container automatically unless explicitly stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}  # Set MariaDB root password from environment variables
      MYSQL_DATABASE: ${MARIADB_DATABASE}  # Set initial MariaDB database from environment variables
      MYSQL_USER: ${MARIADB_USER}  # Set non-root MariaDB user from environment variables
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}  # Set password for non-root user from environment variables
    volumes:
      - /var/www/private/mariadb:/var/lib/mysql  # Mount directory for persistent data storage
hooks:
  up:
    # Copy the custom Nginx configuration to the container
    - command: cp ../nginx/ghost.mojah2.mojahmedia.conf /var/www/private/nginx/conf.d
    - command: docker-compose exec nginx nginx -s reload
  down:
    # Remove the custom Nginx configuration
    - command: rm /var/www/private/nginx/conf.d/one.mojah2.mojahmedia.conf
    - command: docker-compose exec nginx nginx -s reload

networks:
  backend:
    external: true  # Use the existing backend network
